fix branch pushes failing in integration controller since they do not have head_commit
https://zendesk.airbrake.io/projects/95346/groups/2067341449019993699/notices/2067344219670196701?tab=notice-detail

```
NoMethodError: undefined method `[]' for nil:NilClass
```