do not hardcode strategies since they might not be available
phasing out basic atm

RuntimeError: Invalid strategy basic
app/controllers/application_controller.rb:53 in using_per_request_auth?
https://zendesk.airbrake.io/projects/95346/groups/1984304689843743640