fix sporadic runtime errors seen in production due to MRI bug
NoMethodError: undefined method `url_options' for #<Module>
see explanation at https://github.com/puma/puma/issues/647