do not send emails to empty strings, it makes the mailer sad
ArgumentError: An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.

https://zendesk.airbrake.io/projects/95346/groups/2095074524264865998