Use structs over stubs when testing serialized data
Currently samson is setup to use memcached via dalli in all
environemnts, although for our testing we don't really need a persisted
cache store, and it saves us having to install memcached on our CI
server, so we've set the test environment to use a in memory cache.

The problem with this is that you can't actually serialize a stub
object. If you run the following code:
```ruby
Marshal.dump(stub("data", body: stub("body", {})))
```

You'll run into this error:
  > TypeError: no _dump_data is defined for class UnboundMethod

Dalli must either rescue from serlialization errors or uses another
method of serialization avoiding the issue.

Anyways, if you just change the stubs to structs the tests pass with
other caches apart from dalli.